server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

environment:
  datasource:
    url: "jdbc:h2:file:./capitole;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
    username: "sa"
    password: ""
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /openapi.json

